### ISSUE TITLE
cropped images

### ISSUE THREAD

**Issue by bianchimro** [C2DH/miller#15]
@danieleguido  seems like the regexp in:

https://github.com/C2DH/miller/blob/master/miller/services.py#L48

cuts out all of our files (we always have `_` and other non alphanumeric characters in our image urls)

**Comment by danieleguido** [comment]
Hi @bianchimro, image urls have been normalised to "slugs". I've added the `_` character (see line https://github.com/C2DH/miller/blob/master/miller/services.py#L56), but we're going to use IIIF api in the near future
